Repository atlp-rwanda/e-commerce-lydia-32-bn, pull requests merged in 2024-05, with the labels that each got.

#7 Setting up circleci to the project
  .circleci/config.yml
  README.md
Labels: documentation

#33 Fix: correcting 'Email already Exists' error, validations and token storage
  .DS_Store
  README.md
  package.json
  src/.DS_Store
  src/controllers/userController/registeruser.controller.ts
  src/middleware/verfication.middleware.ts
  src/routes/user.route.ts
  src/server.ts
  src/validations/registeruser.validation.ts
Labels: documentation

#40 feature: Setting up user roles and permissions
  dist/src/services/registeruser.service.js
  migrations/20240524115938-create-roles.cjs
  migrations/20240524115939-create-permissions.cjs
  migrations/20240524115940-create-role-permissions.cjs
  migrations/20240527160853-update-users-add-role-id.cjs
  migrations/20240527193239-create-table-users.cjs
  migrations/20240528125933-remove-usertype-from-users.cjs
  migrations/20240528130059-remove-isAdmin-from-users.cjs
  src/controllers/rolesController/roleController.ts
  src/controllers/userController/LoginUserByEmail.controller.ts
  src/controllers/userController/registeruser.controller.ts
  src/middleware/checkAdminRoleMiddleware.ts
  src/middleware/isAdminMiddleware.ts
  src/middleware/verfication.middleware.ts
  src/models/associationsModel.ts
  src/models/permissionModel.ts
  src/models/roleModel.ts
  src/models/rolePermissionModel.ts
  src/models/userModel.ts
  src/routes/roleRoutes.ts
  src/routes/user.route.ts
  src/server.ts
  src/services/registeruser.service.ts
  src/services/roles/roleService.ts
  src/utilis/roles/roles.util.ts
  src/utilis/swagger.ts
  src/validations/registeruser.validation.ts
Labels: Ready

#43 Ft 2fa 187570869: Two Two-factor authentication for Sellers
  dist/src/services/registeruser.service.js
  migrations/20240527180828-add-twoFactorSecret-to-users.cjs
  migrations/20240527203911-add-hasTwoFactor-to-users.cjs
  package.json
  src/controllers/productController/productController.ts
  src/controllers/seller controller/sellerController.ts
  src/controllers/userController/2Factor.controller.ts
  src/controllers/userController/LoginUserByEmail.controller.ts
  src/controllers/userController/loginUser.ts
  src/helpers/sendSms.ts
  src/middleware/isAdminMiddleware.ts
  src/middleware/verfication.middleware.ts
  src/models/userModel.ts
  src/routes/user.route.ts
  src/services/registeruser.service.ts
Labels: Ready

#46 feat(User get product): Have a user be able to get a specific product…
  src/controllers/productController/productController.ts
  src/controllers/seller controller/sellerController.ts
  src/controllers/userController/user.getItem.ts
  src/middleware/checkSellerRole.ts
  src/middleware/validateSearch.ts
  src/routes/productRoutes.ts
  src/routes/sellerRoutes.ts
  src/routes/user.route.ts
  src/services/product.service.ts
  src/services/seller.Service.ts
  src/services/services.ts
  src/validations/getItem.validation.ts
  src/validations/product.validation.ts
Labels: Ready for Peer Preview, changes implemented
