Repository atlp-rwanda/e-commerce-lydia-32-bn, pull requests merged in 2024-06, with the labels that each got.

#55 Refactor 001
  README.md
  src/controllers/wishListController/wishlistsController.ts
  src/routes/wishListRoutes.ts
  src/validations/product.validation.ts
Labels: Ready for Peer Preview

#56 Payment with stripe
  README.md
  src/controllers/wishListController/wishlistsController.ts
  src/routes/wishListRoutes.ts
  src/validations/product.validation.ts
Labels: in progress

#44 A buyer can update their cart and also their total items count will b…
  config/config.json
  src/controllers/cartController/cartControllers.ts
  src/models/cartItemModel.ts
  src/models/index.ts
  src/routes/cartRoutes.ts
  src/services/cart.services.ts
  src/utilis/swagger.ts
Labels: Ready for Peer Preview

#57 Ft seller available products 187570875
  .DS_Store
  src/controllers/userController/loginUser.ts
  src/middleware/authenticateAndAuthorizeUser.ts
  src/routes/user.route.ts
Labels: Ready for Peer Preview

#63 ch(fix-product-validations): Have create and update product controlle…
  src/controllers/productController/productController.ts
  src/middleware/validateSearch.ts
  src/routes/productRoutes.ts
  src/services/product.service.ts
  src/validations/product.validation.ts
Labels: Ready for Peer Preview

#62 ft-Buyer should be Able to checkout #187570890
  migrations/20240604180326-orders.cjs
  migrations/20240604202807-add-orderId-to-carts.cjs
  migrations/20240604204840-add-payment-to-orders.cjs
  migrations/20240604205150-add-address-to-orders.cjs
  migrations/20240604222815-drop-payment-from-orders.cjs
  migrations/20240604223100-add-payment-to-orders.cjs
  migrations/20240604223433-drop-totalAmount-from-orders.cjs
  migrations/20240604223616-add-totalAmount-to-orders.cjs
  migrations/20240605070607-drop-address-from-orders.cjs
  migrations/20240605071449-add-payment-to-orders.cjs
  src/controllers/orderController.ts/checkoutController.ts
  src/helpers/sendSms.ts
  src/middleware/authMiddleware.ts
  src/middleware/authenticateAndAuthorizeUser.ts
  src/middleware/buyerCheckout.ts
  src/models/orderModel.ts
  src/routes/orderRoute.ts
  src/server.ts
  src/services/orderService/orderService.ts
Labels: Ready for Peer Preview

#64 FIX: fixing the roles and permission middleware and default permissions for a role
  migrations/20240605141146-remove-permissions-column-from-roles.cjs
  src/controllers/rolesController/roleController.ts
  src/middleware/checkAdminRoleMiddleware.ts
  src/models/rolePermissionModel.ts
  src/routes/roleRoutes.ts
  src/services/roles/roleService.ts
  src/validations/rolesPermissionsValidations.ts
Labels: Ready for merge

#68 Ft user provide review 187570881
  .circleci/config.yml
  migrations/120240604202232-create-reviews-table.cjs
  package.json
  src/controllers/reviewController/review.controller.ts
  src/middleware/buyerMiddleware.ts
  src/models/review.ts
  src/routes/reviewroute.ts
  src/routes/roleRoutes.ts
  src/server.ts
  src/services/review.service.ts
Labels: Ready for Peer Preview

#65 User Can Mark Notification As Read and Unread #187570891
  src/controllers/notificationController/notificationController.ts
  src/controllers/userController/LoginUserByEmail.controller.ts
  src/controllers/userController/blockUser.controller.ts
  src/controllers/userController/loginUser.ts
  src/controllers/userController/registeruser.controller.ts
  src/middleware/verfication.middleware.ts
  src/models/notificationModels.ts
  src/routes/notificationRoute.ts
  src/routes/roleRoutes.ts
  src/routes/user.route.ts
  src/server.ts
  src/utilis/generateToken.ts
Labels: Ready for merge

#74 chang of cors policy to include hsoted render version
  package.json
  src/server.ts
  src/utilis/swagger.ts
Labels: Ready for merge

#77 Payment with stripe#187570888
  migrations/20240607085241-payments.cjs
  package.json
  src/config/stripe.ts
  src/controllers/paymentController/paymentController.ts
  src/models/paymentModel.ts
  src/routes/paymentsRoutes.ts
  src/server.ts
  src/services/paymentService.ts
  src/utilis/swagger.ts
Labels: Ready for merge

#79 Ft public chat 187570895 Users should be able to chat on the App
  .husky/_/pre-commit
  config/config.mjs
  migrations/120240604202232-create-reviews-table.cjs
  migrations/20240606100434-add-totalPaid-to-orders.cjs
  migrations/20240610130048-create-post.cjs
  migrations/20240610132702-add-name-to-Posts.cjs
  models/post.cjs
  src/config/stripe.ts
  src/controllers/notificationController/notificationController.ts
  src/controllers/orderController.ts/orderStatus.ts
  src/controllers/paymentController/paymentController.ts
  src/controllers/postController/messageController.ts
  src/controllers/reviewController/review.controller.ts
  src/controllers/userController/LoginUserByEmail.controller.ts
  src/controllers/userController/blockUser.controller.ts
  src/controllers/userController/loginUser.ts
  src/controllers/userController/registeruser.controller.ts
  src/middleware/buyerMiddleware.ts
  src/middleware/validateSearch.ts
  src/models/notificationModels.ts
  src/models/orderModel.ts
  src/models/paymentModel.ts
  src/models/postModel.ts
  src/models/review.ts
  src/routes/notificationRoute.ts
  src/routes/orderRoute.ts
  src/routes/paymentsRoutes.ts
  src/routes/postRoutes.ts
  src/routes/reviewroute.ts
  src/routes/roleRoutes.ts
  src/server.ts
  src/services/orderService/orderService.ts
  src/services/paymentService.ts
  src/services/postService/messageService.ts
  src/services/review.service.ts
  src/utilis/generateToken.ts
  src/utilis/orderStatusConstants.ts
Labels: Ready for merge

#78 Notification system for product evolution
  src/.DS_Store
  src/controllers/notificationController/notificationController.ts
  src/controllers/productController/productController.ts
  src/controllers/seller controller/sellerController.ts
  src/controllers/userController/LoginUserByEmail.controller.ts
  src/controllers/userController/blockUser.controller.ts
  src/controllers/userController/loginUser.ts
  src/controllers/userController/registeruser.controller.ts
  src/handles/notifications.service.ts
  src/helpers/sendEmail.ts
  src/middleware/authenticateAndAuthorizeUser.ts
  src/models/cartItemModel.ts
  src/models/orderModel.ts
  src/models/productModel.ts
  src/routes/notificationRoute.ts
  src/server.ts
  src/services/email.constants.ts
  src/services/notification.service.ts
  src/services/product.service.ts
  src/services/registeruser.service.ts
  src/utilis/eventEmitter.ts
  src/utilis/swagger.ts
  tsconfig.json
Labels: Ready for merge

#81 Expirity date functionality - The products should stop listing if the expiry date has passed
  migrations/20240611110935-add-expiryDate-to-products.cjs
  package.json
  src/cronjobs/expiredProductsCron.ts
  src/models/productModel.ts
  src/server.ts
Labels: Ready for merge

#80 Ft password expiration prompt#187570893
  .husky/_/pre-commit
  migrations/20240610134526-remove-passwordExpiresAt-to-users.cjs
  migrations/20240610134819-add-passwordExpiresAt-to-users.cjs
  src/Jobs/passwordExpirationJob.ts
  src/controllers/userController/LoginUserByEmail.controller.ts
  src/controllers/userController/registeruser.controller.ts
  src/middleware/isPasswordExpired.ts
  src/models/userModel.ts
  src/routes/cartRoutes.ts
  src/routes/orderRoute.ts
  src/routes/paymentsRoutes.ts
  src/routes/postRoutes.ts
  src/routes/productRoutes.ts
  src/routes/reviewroute.ts
  src/routes/sellerRoutes.ts
  src/routes/user.route.ts
  src/routes/wishListRoutes.ts
  src/server.ts
  src/services/registeruser.service.ts
Labels: Ready for merge

#82 Modify production details cors policy
  .DS_Store
  src/associations/associations.ts
  src/routes/user.route.ts
  src/server.ts
  tsconfig.json
Labels: Ready for merge

#88 Fixing Permission deletion feature
  src/controllers/rolesController/roleController.ts
  src/routes/notificationRoute.ts
Labels: Ready for merge

#87 correct change password controllers
  Dockerfile.nodejs
  src/controllers/userController/registeruser.controller.ts
Labels: Ready for merge

#86 added .env.example
  .env.example
Labels: Ready for merge

#90 Ft public chat 187570895
  .husky/_/pre-commit
  migrations/20240610134819-add-passwordExpiresAt-to-users.cjs
  migrations/20240611110935-add-expiryDate-to-products.cjs
  migrations/20240615113007-add-room-to-Posts.cjs
  package.json
  src/controllers/cartController/cartControllers.ts
  src/controllers/chatController/chat-controller.ts
  src/controllers/notificationController/notificationController.ts
  src/controllers/orderController.ts/checkoutController.ts
  src/controllers/orderController.ts/orderStatus.ts
  src/controllers/paymentController/paymentController.ts
  src/controllers/postController/messageController.ts
  src/controllers/productController/productController.ts
  src/controllers/userController/blockUser.controller.ts
  src/controllers/userController/deleteItemFromCollection.ts
  src/controllers/userController/getCredentials.controller.ts
  src/controllers/userController/registeruser.controller.ts
  src/cronjobs/expiredProductsCron.ts
  src/middleware/isBuyerMiddleware.ts
  src/middleware/isPasswordExpired.ts
  src/middleware/verfication.middleware.ts
  src/models/orderModel.ts
  src/models/postModel.ts
  src/models/productModel.ts
  src/models/userModel.ts
  src/routes/cartRoutes.ts
  src/routes/orderRoute.ts
  src/routes/paymentsRoutes.ts
  src/routes/postRoutes.ts
  src/routes/productRoutes.ts
  src/routes/reviewroute.ts
  src/routes/sellerRoutes.ts
  src/routes/user.route.ts
  src/routes/wishListRoutes.ts
  src/server.ts
  src/services/cart.services.ts
  src/services/chatService/chat-service.ts
  src/services/email.constants.ts
  src/services/orderService/orderService.ts
  src/services/postService/messageService.ts
  src/services/product.service.ts
  src/services/registeruser.service.ts
  src/services/review.service.ts
  src/services/seller.Service.ts
  src/utilis/Chat/chat.ts
  src/utilis/messages.ts
  src/utilis/swagger.ts
  src/utilis/users.ts
  src/validations/orderValidation.ts
  tsconfig.json
Labels: Ready for Peer Preview

#91 improved payment with stripe and ensured sending emails to sellers an…
  migrations/20240617115026-alter-amount-datatype.cjs
  package.json
  src/config/stripe.ts
  src/controllers/paymentController/paymentController.ts
  src/models/paymentModel.ts
  src/routes/paymentsRoutes.ts
  src/services/product.service.ts
  src/utilis/swagger.ts
Labels: Ready for Peer Preview, Ready for merge

#94 adding notifications for payment and order
  src/controllers/paymentController/paymentController.ts
  src/controllers/productController/productController.ts
  src/handles/notifications.service.ts
  src/middleware/checkSellerRole.ts
  src/models/cartItemModel.ts
  src/models/orderModel.ts
  src/routes/roleRoutes.ts
  src/server.ts
  src/services/cart.services.ts
  src/services/orderService/orderService.ts
  src/utilis/swagger.ts
  tsconfig.json
Labels: in progress
