Repository atlp-rwanda/e-commerce-lydia-32-bn, pull requests merged in 2024-07, with the labels that each got.

#97 Fixing Logout errors
  src/controllers/userController/LoginUserByEmail.controller.ts
  src/middleware/verfication.middleware.ts
Labels: Ready for Peer Preview

#101 send rolePermission data to the client
  src/controllers/rolesController/roleController.ts
  src/routes/roleRoutes.ts
Labels: Ready for Peer Preview

#100 Ft login enhanced
  src/controllers/userController/loginUser.ts
Labels: Ready for Peer Preview

#104 Fixing notification issues and getting seller products
  src/controllers/notificationController/notificationController.ts
  src/controllers/seller controller/sellerController.ts
  src/handles/notifications.service.ts
Labels: Ready for merge

#105 Fixing middleware and controller get token from cookie or header on getting seller products
  src/controllers/seller controller/sellerController.ts
  src/middleware/isPasswordExpired.ts
Labels: Ready for Peer Preview, Ready for merge, changes implemented

#113 Fix creating account default role management
  src/services/registeruser.service.ts
Labels: Ready for Peer Preview

#114 chat app
  src/controllers/chatController/chat-controller.ts
  src/models/postModel.ts
  src/server.ts
  src/services/chatService/chat-service.ts
  src/utilis/Chat/chat.ts
  src/utilis/users.ts
Labels: Ready for Peer Preview
